# What's this for? This file is used by the markdownlinting extension in VSCode, as well as the GitHub actions
# See all rules at https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Ignore line length
"MD013": false

# Allow multiple headings with the same content provided the headings are not "siblings"
"MD024":
    "siblings_only": true

# Allow trailing punctuation in headings
"MD026": false

# Always used fenced code blocks
"MD046":
    "style": "fenced"

